[package]
name = "kbshare-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "kbshare_platform"
path = "src/lib.rs"

[dependencies]
kbshare-core = { path = "../core" }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
crossbeam-channel = { workspace = true }
once_cell = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { version = "=0.9.3", default-features = false, features = ["tokio"] }
evdev = { workspace = true }
futures-util = "0.3"
libc = "0.2"
reis = { version = "0.7", features = ["tokio"] }
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }
x11rb = "0.13"
